### PR TITLE
Input, Output 

### PR DESCRIPTION
**Pull request by dontcallmebigguy**
Amazing work here, I'm a big fan. Here's a small suggestion - 

Let's give users the ability to have custom outputs. 

For example, if the user types in pwd as an input, there should be a directory string as an output. 

This can be done via an Object inserted in the commands array. 

**Example:** commands: ['sudo -i', 'rm -rf /', 'exit', {'input': 'pwd', 'output': ['/Users/Carmelo Anthony']}]

Screen Shot 2020-04-27 at 3 42 26 AM

### CODE REVIEW

**Comment by dontcallmebigguy** [comment]
Please let me know if there's anything else you'd like me to do or help with to make this happen! Thanks.

**Comment by dontcallmebigguy** [comment]
In addition, there is multiline functionality, if the user needs to provide multiple lines in their output. 

**Example:** commands: ['sudo -i', 'rm -rf /', 'exit', {'input': 'ls', 'output': ['Applications  Desktop  Downloads  Movies  Pictures', 'Documents  Library  Music  Public']}]

Screen Shot 2020-04-27 at 8 32 01 AM

**Comment by davidecaruso** [comment]
Hi @dontcallmebigguy, thanks for your contribution. This is very interesting feature and I'm going to merge it. If you have any more suggestions feel free to put your hands-on.

**Comment by dontcallmebigguy** [comment]
Happy to add some examples to your gh-pages branch once the npm version is updated in the registry!

**Pull request merged**
